### ISSUE TITLE
Unable to access some model weights

### ISSUE THREAD

**Issue by benlonnqvist** [brain-score/vision#1196]
When loading some models such as `hmax` or `VideoMAE-V1-B` (and I presume many others), the error of a following kind is thrown:

```Traceback (most recent call last):
  File "C:\Users\loennqvi\Anaconda3\envs\brain-score\lib\site-packages\brainio\fetch.py", line 78, in download_boto
    self.download_boto_config(config=None)
  File "C:\Users\loennqvi\Anaconda3\envs\brain-score\lib\site-packages\brainio\fetch.py", line 94, in download_boto_config
    with tqdm(total=obj.content_length, unit='B', unit_scale=True,
  File "C:\Users\loennqvi\Anaconda3\envs\brain-score\lib\site-packages\boto3\resources\factory.py", line 381, in property_loader
    self.load()
  File "C:\Users\loennqvi\Anaconda3\envs\brain-score\lib\site-packages\boto3\resources\factory.py", line 565, in do_action
    response = action(self, *args, **kwargs)
  File "C:\Users\loennqvi\Anaconda3\envs\brain-score\lib\site-packages\boto3\resources\action.py", line 88, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "C:\Users\loennqvi\Anaconda3\envs\brain-score\lib\site-packages\botocore\client.py", line 553, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\Users\loennqvi\Anaconda3\envs\brain-score\lib\site-packages\botocore\client.py", line 1009, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (404) when calling the HeadObject operation: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\loennqvi\Anaconda3\envs\brain-score\lib\site-packages\brainio\fetch.py", line 84, in download_boto
    self.download_boto_config(config=unsigned_config)
  File "C:\Users\loennqvi\Anaconda3\envs\brain-score\lib\site-packages\brainio\fetch.py", line 94, in download_boto_config
    with tqdm(total=obj.content_length, unit='B', unit_scale=True,
  File "C:\Users\loennqvi\Anaconda3\envs\brain-score\lib\site-packages\boto3\resources\factory.py", line 381, in property_loader
    self.load()
  File "C:\Users\loennqvi\Anaconda3\envs\brain-score\lib\site-packages\boto3\resources\factory.py", line 565, in do_action
    response = action(self, *args, **kwargs)
  File "C:\Users\loennqvi\Anaconda3\envs\brain-score\lib\site-packages\boto3\resources\action.py", line 88, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "C:\Users\loennqvi\Anaconda3\envs\brain-score\lib\site-packages\botocore\client.py", line 553, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\Users\loennqvi\Anaconda3\envs\brain-score\lib\site-packages\botocore\client.py", line 1009, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\loennqvi\Anaconda3\envs\brain-score\lib\site-packages\brainio\fetch.py", line 88, in download_boto
    raise Exception([e_signed, e_unsigned])
Exception: [ClientError('An error occurred (404) when calling the HeadObject operation: Not Found'), ClientError('An error occurred (403) when calling the HeadObject operation: Forbidden')]
python-BaseException
```

This does not seem to happen for all users (e.g., on a different user & machine without `aws` configuration), but it does happen on my machine with an `aws` user configured. It seems like brainio attempts to access the file both with and without my credentials, and both fail for some reason (even though the model files should be publicly accessible).

**Comment by sydddl** [comment]
I encountered the same problem. How did you solve it in the end? Thank you

**Comment by benlonnqvist** [comment]
I did not test whether I solved it or not (I decided it was not worth it) - but we suspected it was because of access right issues with having several (?) accounts on AWS, with either a wrong configuration locally or a python version mismatch. @KartikP @mike-ferguson do you happen to remember? I remember we at some point believed that due to a brain-score backend upgrade this issue would have disappeared.

**Comment by KartikP** [comment]
Hi @sydddl! This is certainly weird. Do you mind sharing details on what code (specifically model/benchmark) you are trying to run? Additionally, `python --version` and `pip list` output would be helpful to make sure everything else is in check. As @benlonnqvist mentioned, if you have other AWS credentials also loaded, that can sometimes create a conflict.

**Comment by sydddl** [comment]
@KartikP  oh, 

I deleted the `.aws` file from the user directory. I created a new conda environment for Python based on your version, I don't think this is the problem, but I'm using Windows. My current solution is to manually download and modify the model.py file.

I encountered a problem with some models when using the load_model command in Brainscore, preventing the model weights from being loaded.

```py
swin_small_patch4_window7_224:ms_in22k_ft_in1k
resnet50-VITO-8deg-cc
voneresnet-50-non_stochastic
AlexNet_SIN
alexnet_training_seed_01
hmax
#------------------------------------

Exception: [ClientError('An error occurred (403) when calling the HeadObject operation: Forbidden'), ClientError('An error occurred (404) when calling the HeadObject operation: Not Found')]
```

I discovered that I could manually access the download. By inserting an output statement in `\vision\brainscore_vision\model_helpers\s3.py`, I found the location of the model weights in the S3 container and the predefined local download location `C:\Users\DeathSprout\.brain-score\brainscore-vision\models`. Then, I need to modify the parameters in the `model.py` file of the faulty model as needed. For example, for the `alexnet_training_seed_0X` series models, I need to:
- Run load_model once to initialize the corresponding folder and program in `D:\github\github_clone\vision\brainscore_vision\models`
- Download the weights file from `https://brainscorevariability.s3.amazonaws.com/models/model_weights/training_seed_03.pth` and place it in the local download directory
- Modify the `model.py` program:
```py
weights_path = load_weight_file(bucket = "brainscorevariability",
relative_path = "model_weights/training_seed_03.pth", version_id = None, sha1 = "6c5a1fdadc70e5007c66866400bfcd7c17280fa8")
#to ->

weights_path = load_weight_file(bucket = "brainscorevariability", folder_name="brainscore-vision/models",
relative_path = "alexnet_training_seed/training_seed_03.pth", version_id = None, sha1 = "6c5a1fdadc70e5007c66866400bfcd7c17280fa8" )
```
- If no errors are reported during the run, I've completed debugging and can add this model to the computational pipeline.

**Comment by sydddl** [comment]
> 嗨 ！这当然很奇怪。您介意分享有关您尝试运行的代码（特别是模型/基准测试）的详细信息吗？此外，输出将有助于确保其他一切都得到检查。如前所述，如果您还加载了其他 AWS 凭证，有时会产生冲突。`python --version``pip list`

I didn't run any benchmarks, just
```python
from brainscore_vision import load_model
model = load_model("alexnet_training_seed_08")
```
I can load most of the available models, but some of them cannot. For example, AlexNet_SIN，it will be :
```python
RuntimeError: unexpected EOF, expected 2038712 more bytes. The file might be corrupted.
```

**Comment by benlonnqvist** [comment]
I remember I also had weird issues with brain-score on Windows that I did not have with WSL. Would it be wise to formally recommend use of WSL for Windows users in general?
