### ISSUE TITLE
Error when checking models, OSError: [Errno 5] Input/output error

### ISSUE THREAD

**Issue by YudiXie** [brain-score/vision#620]
I am trying to submit a model following the tutorial here:
https://www.brain-score.org/tutorial/deepdive_2

However, when I run the local check `check_models.check_base_models(__name__)` I got the following error.

```
[yu_xie@node091 yudixie_resnet50_imagenet1kpret_0_240222]$ python model.py
/om/user/yu_xie/miniconda3/envs/brainscore/lib/python3.7/site-packages/brainscore_core/metrics/__init__.py:16: FutureWarning: xarray subclass Score should explicitly define __slots__
  class Score(DataAssembly):
Loaded model from yudixie_resnet50_imagenet1kpret_0_240222_weights.pth
Loaded model from yudixie_resnet50_imagenet1kpret_0_240222_weights.pth
Traceback (most recent call last):
  File "model.py", line 67, in <module>
    check_models.check_base_models(__name__)
  File "/weka/scratch/weka/dicarlo/yu_xie/projects/brain-score/brainscore_vision/model_helpers/check_submission/check_models.py", line 38, in check_base_models
    check_processing(model, module)
  File "/weka/scratch/weka/dicarlo/yu_xie/projects/brain-score/brainscore_vision/model_helpers/check_submission/check_models.py", line 46, in check_processing
    benchmark = _MockBenchmark()
  File "/weka/scratch/weka/dicarlo/yu_xie/projects/brain-score/brainscore_vision/model_helpers/check_submission/check_models.py", line 61, in __init__
    assembly_repetition = load_dataset("MajajHong2015.public").sel(region="IT").squeeze("time_bin")
  File "/weka/scratch/weka/dicarlo/yu_xie/projects/brain-score/brainscore_vision/__init__.py", line 34, in load_dataset
    return data_registry[identifier]()
  File "/weka/scratch/weka/dicarlo/yu_xie/projects/brain-score/brainscore_vision/data/majajhong2015/__init__.py", line 55, in <lambda>
    stimulus_set_loader=lambda: brainscore_vision.load_stimulus_set('hvm-public'),
  File "/weka/scratch/weka/dicarlo/yu_xie/projects/brain-score/brainscore_vision/data_helpers/s3.py", line 42, in load_assembly_from_s3
    stimulus_set = stimulus_set_loader()
  File "/weka/scratch/weka/dicarlo/yu_xie/projects/brain-score/brainscore_vision/data/majajhong2015/__init__.py", line 55, in <lambda>
    stimulus_set_loader=lambda: brainscore_vision.load_stimulus_set('hvm-public'),
  File "/weka/scratch/weka/dicarlo/yu_xie/projects/brain-score/brainscore_vision/__init__.py", line 41, in load_stimulus_set
    return stimulus_set_registry[identifier]()
  File "/weka/scratch/weka/dicarlo/yu_xie/projects/brain-score/brainscore_vision/data/majajhong2015/__init__.py", line 104, in <lambda>
    zip_version_id="UzgkNOtIWMXaMN7vUA0FVemXLTvdtH13")
  File "/weka/scratch/weka/dicarlo/yu_xie/projects/brain-score/brainscore_vision/data_helpers/s3.py", line 67, in load_stimulus_set_from_s3
    stimuli_paths = [Path(stimuli_directory) / local_path for local_path in os.listdir(stimuli_directory)
OSError: [Errno 5] Input/output error: '/home/yu_xie/.brainio/image_dicarlo_hvm-public'
```

**Comment by mschrimpf** [comment]
This seems to be an OS error from the call to `os.listdir`.
Is that directory somehow exceedingly large? (maybe related: https://stackoverflow.com/q/66747762/2225200)

**Comment by mike-ferguson** [comment]
This can also occur (according to some other internet sources) if either memory or disk space has been exceeded. Are you maxing out a storage quota anywhere?

**Comment by YudiXie** [comment]
I just checked, and I have ample space on the disk

**Comment by mike-ferguson** [comment]
Gotcha- do you have read/write permissions for `/home/yu_xie/.brainio/image_dicarlo_hvm-public`?

 @mschrimpf is this indicative of something we need to change in `load_stimulus_set_from_s3`?

**Comment by YudiXie** [comment]
Yes, I have. 
If this information helps: `/home/yu_xie/.brainio` is a symbolic link to a directory on `om`. I use this because openmind has a small home quota.

**Comment by mschrimpf** [comment]
we have used this function for the last years without a problem, so my guess would be that this is random OpenMind shenanigans. FWIW I did sometimes see similar OS errors (outside of Brain-Score for other code) with a similar symlink setup

**Comment by YudiXie** [comment]
I tried to test this multiple times on openmind at different times during the day, and this error persists. Have people been able to run `check_models.check_base_models(__name__)` successfully on openmind?

**Comment by mike-ferguson** [comment]
We have had test runs on Openmind of the check_models function, but I will confirm this again

**Comment by mike-ferguson** [comment]
@YudiXie Just wanted to follow up on this
