### ISSUE TITLE
Problem loading MajajHong2015public.IT-pls

### ISSUE THREAD

**Issue by YingtianDt** [brain-score/vision#677]
Hi, I got the following error when trying `benchmark = load_benchmark("MajajHong2015public.IT-pls")`:

```
Traceback (most recent call last):
  File "test.py", line 20, in <module>
    benchmark = load_benchmark("MajajHong2015public.IT-pls")
  File "/home/ytang/workspace/brain-score/brainscore_vision/__init__.py", line 61, in load_benchmark
    return benchmark_registry[identifier]()
  File "/home/ytang/workspace/brain-score/brainscore_vision/benchmarks/majajhong2015/benchmark.py", line 60, in MajajHongITPublicBenchmark
    ceiler=load_ceiling('internal_consistency'))
  File "/home/ytang/workspace/brain-score/brainscore_vision/benchmarks/majajhong2015/benchmark.py", line 28, in _DicarloMajajHong2015Region
    assembly_repetition = load_assembly(average_repetitions=False, region=region, access=access)
  File "/home/ytang/workspace/brain-score/brainscore_vision/benchmarks/majajhong2015/benchmark.py", line 64, in load_assembly
    assembly = load_dataset(f'MajajHong2015.{access}')
  File "/home/ytang/workspace/brain-score/brainscore_vision/__init__.py", line 34, in load_dataset
    return data_registry[identifier]()
  File "/home/ytang/workspace/brain-score/brainscore_vision/data/majajhong2015/__init__.py", line 55, in <lambda>
    stimulus_set_loader=lambda: brainscore_vision.load_stimulus_set('hvm-public'),
  File "/home/ytang/workspace/brain-score/brainscore_vision/data_helpers/s3.py", line 49, in load_assembly_from_s3
    assembly = loader.load()
  File "/home/ytang/miniconda3/envs/temp/lib/python3.7/site-packages/brainio/assemblies.py", line 499, in load
    result = super(StimulusMergeAssemblyLoader, self).load()
  File "/home/ytang/miniconda3/envs/temp/lib/python3.7/site-packages/brainio/assemblies.py", line 487, in load
    result = super(StimulusReferenceAssemblyLoader, self).load()
  File "/home/ytang/miniconda3/envs/temp/lib/python3.7/site-packages/brainio/assemblies.py", line 459, in load
    result = xr.open_dataarray(self.file_path, group=self.group, chunks=chunks)
  File "/home/ytang/miniconda3/envs/temp/lib/python3.7/site-packages/xarray/backends/api.py", line 666, in open_dataarray
    **kwargs,
  File "/home/ytang/miniconda3/envs/temp/lib/python3.7/site-packages/xarray/backends/api.py", line 479, in open_dataset
    engine = plugins.guess_engine(filename_or_obj)
  File "/home/ytang/miniconda3/envs/temp/lib/python3.7/site-packages/xarray/backends/plugins.py", line 110, in guess_engine
    engines = list_engines()
  File "/home/ytang/miniconda3/envs/temp/lib/python3.7/site-packages/xarray/backends/plugins.py", line 105, in list_engines
    entrypoints = entry_points().get("xarray.backends", ())
AttributeError: 'EntryPoints' object has no attribute 'get'
```

**Comment by mschrimpf** [comment]
@mike-ferguson the EntryPoints stuff sounds like catalog -- any chance you know what to fix here?

**Comment by mike-ferguson** [comment]
I will look into this - stand by!

**Comment by YingtianDt** [comment]
Sorry, this turns out to have nothing to do with brainscore_vision itself. It might be the version of importlib-metadata that caused the problem (see a stackoverflow question [here](https://stackoverflow.com/questions/73929564/entrypoints-object-has-no-attribute-get-digital-ocean)). I am closing this issue.
